backend:
  name: github
  repo: kitashimauni/techblog
  branch: main
  base_url: https://techblog-cms-auth.kitashima-daiki123.workers.dev/
logo_url: "https://tech.n-island.dev/favicon.ico"
media_folder: "/assets"
public_folder: "/assets"
collections:
  - name: "techblog"
    label: "techblog"
    folder: "content/posts"
    media_folder: "/{{year}}{{month}}{{day}}-{{url_title}}/src"
    public_folder: "/src"
    create: true
    format: "toml-frontmatter"
    extension: "md"
    path: "{{year}}{{month}}{{day}}-{{url_title}}/index"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "url_title", name: "url_title", widget: "string"}
      - {label: "summary", name: "summary", widget: "string", required: false}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "lastmod", name: "lastmod", widget: "datetime"}
      - {label: "draft", name: "draft", widget: "boolean", default: true}
      - {label: "tags", name: "tags", widget: "list", required: false}
      - {label: "aliases", name: "aliases", widget: "list", required: false}
      - {label: "body", name: "body", widget: "markdown"}
view_filters:
  - label: "Drafts"
    field: "draft"
    pattern: true
