backend:
  name: github
  repo: kitashimauni/techblog
  branch: main
  base_url: https://techblog-cms-auth.kitashima-daiki123.workers.dev/
publish_mode: editorial_workflow
media_folder: "/assets"
public_folder: "/assets"
collections:
  - name: "techblog"
    label: "techblog"
    folder: "content/posts"
    media_folder: "/src"
    public_folder: "/src"
    create: true
    identifier_field: "slug"
    path: "{{year}}{{month}}{{day}}-{{url_title}}/index"
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "url_title", name: "url_title", widget: "string"}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "draft", name: "draft", widget: "boolean", default: true}
      - {label: "tags", name: "tags", widget: "list", required: false}
      - {label: "body", name: "body", widget: "markdown"}
